### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by jas99** [sameersbn/docker-apt-cacher-ng#1]
Hi Sameer
When I use you image in virtualbox with sharing ntfs drive and create my volume on the shared ntfs drive I get permission issues. Maybe there is someway around this. Let me know.

Thx
Jas99

**Comment by sameersbn** [comment]
I am not aware of any workarounds for this. You can create a EXT3 volume and use it instead.

**Comment by strarsis** [comment]
You can actually force user, group + default permissions for a CIFS mount.
http://unix.stackexchange.com/questions/68079/mount-cifs-network-drive-write-permissions-and-chown

With best regards

**Comment by sameersbn** [comment]
@jas99 did @strarsis suggestion help?
Closing the issue for now, please re-open if you need help
