### ISSUE TITLE
automatic cache expiry?

### ISSUE THREAD

**Issue by victornoel** [sameersbn/docker-apt-cacher-ng#11]
Hi,

apt-cacher-ng distributes a cron script for daily cache expiry.

I don't think this docker image ever run it, I suppose because it would mean running cron on top of apt-cacher-ng…

It would be quite useful to do so…

**Comment by sameersbn** [comment]
@victornoel Thanks for the tip. I was not aware of this.
Since we don't want to run `crond` inside the container, we can add a cron entry on the host to execute the job, i.e. add a job to execute `docker exec -it <CONTAINER-NAME> /etc/cron.daily/apt-cacher-ng`
