### ISSUE TITLE
Log to stdout/docker

### ISSUE THREAD

**Issue by strarsis** [sameersbn/docker-apt-cacher-ng#2]
It would be great if apt-cacher-ng could log to stdout so one can attach to the logs using docker logs 
to view the current requests made to it for debugging.

**Comment by sameersbn** [comment]
At the moment there is no such option. As a workaround you can do `docker exec -it apt-cacher-ng tail -f /var/log/apt-cacher-ng/apt-cacher.log`

**Comment by silkentrance** [comment]
@sameersbn in my dockerfile I create symlinks for both /var/log/apt-cacher-ng/apt-cacher.log and /var/log/apt-cacher-ng.err. Both then simply point to /dev/stdout and /dev/stderr, respectively.

**Comment by sameersbn** [comment]
Its been a while, but the thing about the symlinking is that it requires apt-cacher-ng to be launched as the root user. IMO it's not worth the risk.

`docker exec -it apt-cacher-ng tail -f /var/log/apt-cacher-ng/apt-cacher.log` is the recommended way to view the logs of the apt-cache-ng daemon in the image. I will document this option and close this issue.

**Comment by sameersbn** [comment]
actually it has already been documented. closing...

**Comment by DeadNews** [comment]
@sameersbn 

>the thing about the symlinking is that it requires apt-cacher-ng to be launched as the root user. IMO it's not worth the risk.

Why not do this at the image build stage?

Example from the [documentation](https://docs.docker.com/engine/logging/):

> The official nginx image creates a symbolic link from `/var/log/nginx/access.log` to `/dev/stdout`, and creates another symbolic link from `/var/log/nginx/error.log` to `/dev/stderr`, overwriting the log files and causing logs to be sent to the relevant special device instead. See the [Dockerfile](https://github.com/nginxinc/docker-nginx/blob/8921999083def7ba43a06fabd5f80e4406651353/mainline/jessie/Dockerfile#L21-L23).
