### ISSUE TITLE
What is the difference between docker-apt-cacher-ng and the official tutorial

### ISSUE THREAD

**Issue by jacktan1991** [sameersbn/docker-apt-cacher-ng#4]
This is the official tutorial: https://docs.docker.com/engine/examples/apt-cacher-ng/

I want to know the difference. Does docker-apt-cacher-ng add some extra features?

**Comment by sameersbn** [comment]
@jacktan1991 sorry for the lateness of my response. this image does not add any specific features over the https://docs.docker.com/engine/examples/apt-cacher-ng/.
